name: "CF CLI Action"
description: "Deploy and manage Cloud Foundry using the cf cli"
branding:
  icon: "upload-cloud"
  color: "blue"
inputs:
  cf_api:
    description: "Target API Endpoint of Cloud Foundry"
    required: true
  cf_username:
    description: "Username for API authentication"
    required: true
  cf_password:
    description: "Password for API authentication"
    required: true
  cf_org:
    description: "Target Organization"
    required: true
  cf_space:
    description: "Target Space"
    required: true
  docker_passwrd:
    description: "Target dockerhub password"
    required: false
  command:
    description: "Command to run using CF CLI"
    required: true
runs:
  using: "docker"
  image: "docker://croziernn/daze-cldry-cli:v1"
  args:
    - ${{ inputs.command }}
