name: Docker Build (V1)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag croziernn/daze-cldry-cli:v1
    - name: Tag Docker Image
      run: docker tag croziernn/daze-cldry-cli:v1 croziernn/daze-cldry-cli:v1
